name: Denver Devs Gigs Day
on:
  schedule:
    - cron: "0 16 * * 4"
jobs:
  post:
    runs-on: ubuntu-latest
    env:
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: npm install && node ./gigs.js
